#define INFO_PROGRAM   "WinGraph"
#define INFO_VERSION   "2.5.2"
#define INFO_AUTHOR    "Stefan Hüsges"
#define INFO_COPYRIGHT "© 2002 - 2015 by Stefan Hüsges"
#define INFO_HOMEPAGE  "http://www.mpcx.net"
#define INFO_GITHUB    "http://git.io/p4az"
