#define INFO_PROGRAMM    "WinGraph"
#define INFO_VERSION     "2.5.1.0"
#define INFO_AUTOR       "Stefan Hüsges"
#define INFO_COPYRIGHT   "© 2002 - 2014 by Stefan Hüsges"
#define INFO_HOMEPAGE    "http:\/\/www.mpcx.net"
